'use client'
import { useCallback, useEffect, useState } from 'react'
import { Check, Loader2, RefreshCw, ShieldCheck, X } from 'lucide-react'
import AdminShell from '../../../components/AdminShell'

type RefundRow={id:string;amount_paise:number;reason:string;status:string;auto_eligible:boolean;created_at:string;review_note:string|null;profiles:{name:string|null;email:string|null}|null}
const money=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(paise/100)

export default function AdminWalletPage(){
 const [rows,setRows]=useState<RefundRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(()=>{setLoading(true);fetch('/api/admin/refunds').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Refund queue could not be loaded.');setRows(d.refunds||[])}).catch(e=>setError(e instanceof Error?e.message:'Refund queue could not be loaded.')).finally(()=>setLoading(false))},[])
 useEffect(()=>load(),[load])
 const review=async(id:string,decision:'approve'|'reject')=>{setBusy(id);setError('');setMessage('');try{const response=await fetch('/api/admin/refunds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id,decision})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Refund review failed.');setMessage(decision==='approve'?'Refund sent to the original payment method.':'Request rejected and wallet hold released.');load()}catch(e){setError(e instanceof Error?e.message:'Refund review failed.')}finally{setBusy('')}}
 return <AdminShell eyebrow="Wallet operations" title="Refund review" description="Approve eligible Razorpay returns or reject requests to release their reserved wallet funds.">{error&&<div role="alert" className="mt-6 border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{message&&<div role="status" className="mt-6 border border-green-200 bg-green-50 p-4 text-sm text-green-800">{message}</div>}<div className="mt-8 flex items-center justify-between"><p className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="text-[#397354]"/>Server-authorized review queue</p><button onClick={load} className="button button-light"><RefreshCw/>Refresh</button></div>{loading?<Loader2 className="mx-auto mt-12 animate-spin"/>:rows.length===0?<section className="surface-card mt-6 p-10 text-center"><h2 className="text-xl font-black">No refund requests</h2><p className="mt-2 text-sm text-[#6f625f]">New customer requests will appear here.</p></section>:<div className="mt-6 grid gap-4">{rows.map(row=><article key={row.id} className="surface-card grid gap-5 p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><strong className="text-2xl">{money(row.amount_paise)}</strong><span className="rounded-full bg-[#f1e4cf] px-3 py-1 text-xs font-black uppercase">{row.status}</span><span className={`text-xs font-black uppercase ${row.auto_eligible?'text-[#397354]':'text-amber-700'}`}>{row.auto_eligible?'Automatic Razorpay return':'Manual review'}</span></div><p className="mt-3 font-bold">{row.profiles?.name||'Customer'} · {row.profiles?.email||'No email'}</p><p className="mt-1 text-sm text-[#6f625f]">{row.reason}</p><p className="mt-2 text-xs text-[#6f625f]">{new Date(row.created_at).toLocaleString('en-IN')}</p></div>{row.status==='pending'?<div className="flex flex-wrap gap-2"><button disabled={busy===row.id||!row.auto_eligible} onClick={()=>review(row.id,'approve')} className="button bg-[#397354] text-white disabled:opacity-40">{busy===row.id?<Loader2 className="animate-spin"/>:<Check/>}Approve & refund</button><button disabled={busy===row.id} onClick={()=>review(row.id,'reject')} className="button border border-red-200 bg-white text-red-700"><X/>Reject</button></div>:null}</article>)}</div>}</AdminShell>
}
