'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Calendar, CheckCircle2, ChevronRight, Loader2, MapPin, Minus, Pause, Play, Plus, Trash2 } from 'lucide-react'
import Navigation from '../../components/Navigation'
import { PRICING_NOTE } from '../../config/plans'
import { useUser } from '../../hooks/useUser'
import type { Apartment } from '../../types/database'
import type { MockSubscription } from '../../utils/mockDb'

type BundleId='basic'|'standard'|'family'
const BUNDLES:{id:BundleId;name:string;qty:number;color:string;note:string}[]=[
  {id:'basic',name:'Basic',qty:10,color:'#f5c974',note:'A compact everyday top-up'},
  {id:'standard',name:'Standard',qty:20,color:'#e77a4a',note:'A balanced household bundle'},
  {id:'family',name:'Family',qty:32,color:'#587b61',note:'Made for a fuller table'},
]
const DAYS=[['monday','Mon'],['tuesday','Tue'],['wednesday','Wed'],['thursday','Thu'],['friday','Fri'],['saturday','Sat'],['sunday','Sun']]

export default function SubscriptionPage(){
 const {user,loading}=useUser(); const [apartments,setApartments]=useState<Apartment[]>([]); const [activeSub,setActiveSub]=useState<MockSubscription|null>(null)
 const [counts,setCounts]=useState<Record<BundleId,number>>({basic:0,standard:1,family:0}); const [selectedApartment,setSelectedApartment]=useState(''); const [selectedDays,setSelectedDays]=useState(['monday','tuesday','wednesday','thursday','friday']); const [submitting,setSubmitting]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null)
 const [startDate,setStartDate]=useState(()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().split('T')[0]})
 const total=useMemo(()=>BUNDLES.reduce((sum,b)=>sum+counts[b.id]*b.qty,0),[counts]); const primary=BUNDLES.reduce((a,b)=>counts[b.id]>counts[a.id]?b:a,BUNDLES[0])
 useEffect(()=>{
   if(!user){setActiveSub(null);return}
   Promise.all([
     fetch('/api/apartments/list').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load apartments.');return d.apartments as Apartment[]}),
     fetch('/api/subscriptions/current').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load your subscription.');return d.subscription as MockSubscription|null}),
   ]).then(([a,sub])=>{setApartments(a);setSelectedApartment(a[0]?.id||'');setActiveSub(sub)}).catch(err=>setError(err instanceof Error?err.message:'Unable to load subscription details.'))
 },[user])
 const change=(id:BundleId,delta:number)=>setCounts(c=>({...c,[id]:Math.max(0,Math.min(9,c[id]+delta))}))
 const toggleDay=(id:string)=>setSelectedDays(d=>d.includes(id)?d.filter(x=>x!==id):[...d,id])
 async function create(e:React.FormEvent){e.preventDefault();setError(null);if(!user)return;if(!total)return setError('Add at least one bundle to continue.');if(!selectedDays.length)return setError('Choose at least one delivery day.');setSubmitting(true);try{const res=await fetch('/api/subscriptions/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:primary.id,mealsPerWeek:selectedDays.length,startDate,apartmentId:selectedApartment||undefined,quantity:total,daysSelected:selectedDays,bundles:counts})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to create subscription.');const sub:MockSubscription={...data.subscription,quantity:total,days_selected:selectedDays,paused:false};setActiveSub(sub);setMessage('Your delivery schedule is now active.')}catch(err){setError(err instanceof Error?err.message:'Unable to create subscription. Please try again.')}finally{setSubmitting(false)}}
 async function status(action:'pause'|'resume'){if(!activeSub)return;setSubmitting(true);setError(null);try{const res=await fetch(`/api/subscriptions/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscriptionId:activeSub.id})});const data=await res.json();if(!res.ok)throw new Error(data.error||`Could not ${action} this subscription.`);const updated={...activeSub,paused:action==='pause',status:action==='pause'?'paused' as const:'active' as const};setActiveSub(updated);setMessage(`Subscription ${action}d.`)}catch(err){setError(err instanceof Error?err.message:'Something went wrong.')}finally{setSubmitting(false)}}
 async function cancel(){if(!activeSub||!confirm('Cancel all future deliveries?'))return;setSubmitting(true);setError(null);try{const res=await fetch('/api/subscriptions/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscriptionId:activeSub.id})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not cancel this subscription.');setActiveSub(null);setMessage('Subscription cancelled. No future deliveries will be created.')}catch(err){setError(err instanceof Error?err.message:'Could not cancel this subscription.')}finally{setSubmitting(false)}}
 if(loading)return <div className="kitchen-canvas flex min-h-screen items-center justify-center"><Loader2 aria-label="Loading your account" className="h-8 w-8 animate-spin text-[#e56b35]"/></div>
 return <div className="kitchen-canvas min-h-screen"><Navigation/><main className="relative z-10 lg:pl-64"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:py-14">
   <header className="mb-9"><p className="eyebrow text-[#bb4824]">Fresh delivery plan</p><h1 className="editorial-title mt-3 text-5xl font-black sm:text-6xl">Build your chapati bundle.</h1><p className="mt-4 max-w-2xl text-[#6f625f]">Combine bundle sizes for each selected delivery. Basic 10 is ₹99, Standard 20 is ₹179, and Family 32 is ₹259 per selected delivery.</p><p className="mt-2 text-xs font-semibold text-[#6f625f]">{PRICING_NOTE}</p></header>
   {message&&<div role="status" className="mb-6 flex gap-3 rounded-xl border border-[#bcd0c1] bg-[#edf5ef] p-4 text-sm font-semibold text-[#28543d]"><CheckCircle2 className="h-5 w-5"/>{message}</div>}{error&&<div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>}
   {!user?<section className="paper-card mx-auto max-w-xl rounded-[2rem] p-8 text-center sm:p-12"><Calendar className="mx-auto h-10 w-10 text-[#e56b35]"/><h2 className="mt-5 text-3xl font-black">Sign in to set your table.</h2><p className="mt-3 leading-7 text-[#6f625f]">Your chosen bundles and delivery days are linked securely to your account.</p><Link href="/login" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#321c31] px-6 py-3.5 font-bold text-white">Log in to continue <ChevronRight className="h-5 w-5"/></Link></section>:activeSub?<section className="paper-card rounded-[2rem] p-6 sm:p-9"><div className="flex flex-col justify-between gap-5 border-b border-[#eadfce] pb-7 sm:flex-row"><div><div className="flex gap-2"><span className="rounded-md bg-[#f1e4cf] px-2 py-1 text-xs font-black uppercase">{activeSub.plan}</span><span className={`rounded-md px-2 py-1 text-xs font-black uppercase ${activeSub.paused?'bg-amber-100 text-amber-800':'bg-[#dcecdf] text-[#28543d]'}`}>{activeSub.paused?'Paused':'Active'}</span></div><h2 className="mt-4 text-3xl font-black">Your current delivery</h2></div><div className="flex flex-wrap gap-2">{activeSub.paused?<button disabled={submitting} onClick={()=>status('resume')} className="flex items-center gap-2 rounded-xl bg-[#397354] px-4 py-3 text-sm font-bold text-white"><Play className="h-4 w-4"/>Resume</button>:<button disabled={submitting} onClick={()=>status('pause')} className="flex items-center gap-2 rounded-xl border border-[#cdbca6] px-4 py-3 text-sm font-bold"><Pause className="h-4 w-4"/>Pause</button>}<button disabled={submitting} onClick={cancel} className="flex items-center gap-2 rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700"><Trash2 className="h-4 w-4"/>Cancel</button></div></div><div className="grid gap-8 pt-8 sm:grid-cols-3"><div><p className="eyebrow text-[#6f625f]">Per delivery</p><p className="tabular mt-2 text-4xl font-black">{activeSub.quantity} <span className="text-base font-semibold">chapatis</span></p></div><div><p className="eyebrow text-[#6f625f]">Weekly rhythm</p><p className="mt-2 font-bold capitalize">{activeSub.days_selected.join(', ')}</p></div><div><p className="eyebrow text-[#6f625f]">Starts</p><p className="mt-2 font-bold">{activeSub.start_date}</p></div></div></section>:
   <form onSubmit={create} className="grid items-start gap-7 lg:grid-cols-[1fr_340px]"><div className="space-y-7"><section className="paper-card rounded-[2rem] p-5 sm:p-8"><div className="mb-6"><p className="eyebrow text-[#397354]">Step 1 · Quantity</p><h2 className="mt-2 text-2xl font-black">Mix your bundles</h2></div><div className="space-y-3">{BUNDLES.map(b=><article key={b.id} className="flex flex-col justify-between gap-5 rounded-2xl border border-[#dfd0bd] bg-[#fffdf8] p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="tabular flex h-16 w-16 items-center justify-center rounded-2xl text-2xl font-black" style={{background:b.color,color:b.id==='family'?'white':'#321c31'}}>{b.qty}</span><div><h3 className="font-black">{b.name}</h3><p className="mt-1 text-sm text-[#6f625f]">{b.note}</p></div></div><div className="flex items-center justify-end gap-3"><button type="button" aria-label={`Remove one ${b.name} bundle`} onClick={()=>change(b.id,-1)} className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#cdbca6] bg-white"><Minus className="h-4 w-4"/></button><output className="tabular w-7 text-center text-xl font-black">{counts[b.id]}</output><button type="button" aria-label={`Add one ${b.name} bundle`} onClick={()=>change(b.id,1)} className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#321c31] text-white"><Plus className="h-4 w-4"/></button></div></article>)}</div></section>
   <section className="paper-card rounded-[2rem] p-5 sm:p-8"><p className="eyebrow text-[#397354]">Step 2 · Schedule</p><h2 className="mt-2 text-2xl font-black">Choose your delivery days</h2><div className="mt-6 flex flex-wrap gap-2">{DAYS.map(([id,label])=><button key={id} type="button" aria-pressed={selectedDays.includes(id)} onClick={()=>toggleDay(id)} className={`h-12 min-w-12 rounded-xl border px-3 text-sm font-black ${selectedDays.includes(id)?'border-[#321c31] bg-[#321c31] text-white':'border-[#cdbca6] bg-white'}`}>{label}</button>)}</div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold"><span className="mb-2 flex items-center gap-2"><MapPin className="h-4 w-4"/>Apartment</span><select required value={selectedApartment} onChange={e=>setSelectedApartment(e.target.value)} className="w-full rounded-xl border border-[#cdbca6] bg-white p-3.5 font-normal">{apartments.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-sm font-bold"><span className="mb-2 flex items-center gap-2"><Calendar className="h-4 w-4"/>Start date</span><input required type="date" min={startDate} value={startDate} onChange={e=>setStartDate(e.target.value)} className="w-full rounded-xl border border-[#cdbca6] bg-white p-3.5 font-normal"/></label></div></section></div>
   <aside className="sticky top-24 rounded-[2rem] bg-[#321c31] p-7 text-white shadow-xl"><p className="eyebrow text-[#f5c974]">Your delivery</p><div className="mt-7 border-b border-white/15 pb-7"><output className="tabular block text-7xl font-black tracking-[-.06em]">{total}</output><span className="text-sm font-bold text-white/60">chapatis per selected date</span></div><div className="space-y-3 py-6">{BUNDLES.filter(b=>counts[b.id]).map(b=><div key={b.id} className="flex justify-between text-sm"><span className="text-white/65">{counts[b.id]} × {b.name}</span><strong>{counts[b.id]*b.qty}</strong></div>)}{!total&&<p className="text-sm text-white/55">Add a bundle to see your breakdown.</p>}</div><p className="mb-5 text-xs leading-5 text-white/55">Pricing is configured at checkout. No wallet deduction happens on this screen.</p><button type="submit" disabled={submitting||!total} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#e56b35] px-5 py-4 font-black text-white hover:bg-[#bb4824] disabled:opacity-40">{submitting?<Loader2 className="h-5 w-5 animate-spin"/>:<>Confirm schedule <ChevronRight className="h-5 w-5"/></>}</button></aside></form>}
 </div></main></div>
}
