'use client'
import { useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ChevronLeft,ChevronRight,Info,Loader2 } from 'lucide-react'
import Navigation from '../../components/Navigation'
import { useUser } from '../../hooks/useUser'
type Delivery={id:string;delivery_date:string;quantity:number;status:string;amount_paise:number}
const statusColor:Record<string,string>={scheduled:'border-[#397354] bg-[#edf5ef]',preparing:'border-amber-500 bg-amber-50',out_for_delivery:'border-[#e56b35] bg-[#fff3df]',delivered:'border-gray-400 bg-gray-100',cancelled:'border-red-300 bg-red-50'}
export default function CalendarPage(){
 const {user,loading}=useUser();const router=useRouter();const [date,setDate]=useState(()=>new Date());const [deliveries,setDeliveries]=useState<Delivery[]>([]);const [fetching,setFetching]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{if(!loading&&!user)router.replace('/login?next=/calendar')},[loading,user,router])
 const month=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`
 useEffect(()=>{if(!user)return;Promise.resolve().then(()=>{setFetching(true);setError('');return fetch(`/api/deliveries?month=${month}`)}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to load deliveries.');return body.deliveries as Delivery[]}).then(setDeliveries).catch(issue=>setError(issue instanceof Error?issue.message:'Unable to load deliveries.')).finally(()=>setFetching(false))},[user,month])
 const days=useMemo(()=>{const y=date.getFullYear(),m=date.getMonth(),offset=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>i+1)]},[date]);const byDay=new Map(deliveries.map(delivery=>[Number(delivery.delivery_date.slice(-2)),delivery]))
 if(loading||!user)return <div className="app-surface flex items-center justify-center"><Loader2 className="animate-spin text-[#e56b35]"/></div>;const label=date.toLocaleDateString('en-IN',{month:'long',year:'numeric'})
 return <div className="app-surface"><Navigation/><div className="lg:pl-64"><main className="mx-auto max-w-6xl px-4 py-10 sm:px-8"><header className="border-b border-[#dfd0bd] pb-8"><p className="eyebrow text-[#bb4824]">Delivery rhythm</p><h1 className="editorial-title mt-3 text-5xl font-black sm:text-6xl">Your calendar.</h1><p className="mt-4 max-w-2xl leading-7 text-[#6f625f]">Paid and confirmed delivery dates appear here directly from DailyNest.</p></header>{error&&<div role="alert" className="mt-6 border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}<section className="mt-8 grid gap-6 lg:grid-cols-[1fr_19rem]"><div className="surface-card min-w-0 p-4 sm:p-7"><div className="flex items-center justify-between border-b border-[#eadfce] pb-5"><h2 className="text-xl font-black">{label}</h2><div className="flex gap-2"><button aria-label="Previous month" className="button button-outline !min-h-10 !p-2" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()-1,1))}><ChevronLeft/></button><button aria-label="Next month" className="button button-outline !min-h-10 !p-2" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()+1,1))}><ChevronRight/></button></div></div><div className="mt-5 grid grid-cols-7 text-center text-[.65rem] font-black uppercase tracking-wider text-[#6f625f]">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><span key={day}>{day}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1 sm:gap-2">{days.map((day,index)=>{if(day===null)return <span key={`e${index}`}/>;const delivery=byDay.get(day);return <div key={day} className={`aspect-square min-h-12 rounded-lg border p-1.5 text-sm ${delivery?(statusColor[delivery.status]||'border-[#397354] bg-[#edf5ef]'):'border-[#eadfce] bg-[#fffdf8]'}`} aria-label={delivery?`${day} ${label}, ${delivery.quantity} chapatis, ${delivery.status}`:`${day} ${label}`}><strong>{day}</strong>{delivery&&<span className="mt-1 block text-[.6rem] font-black leading-tight">{delivery.quantity} · {delivery.status.replaceAll('_',' ')}</span>}</div>})}</div>{fetching&&<Loader2 className="mx-auto mt-5 animate-spin text-[#e56b35]"/>}</div><aside className="surface-card self-start p-6"><Info className="text-[#397354]"/><h2 className="mt-4 text-xl font-black">This month</h2><p className="mt-3 text-sm leading-6 text-[#6f625f]">{deliveries.length?`${deliveries.length} confirmed delivery dates.`:'No confirmed deliveries in this month.'}</p><Link href="/subscription" className="button button-dark mt-6 w-full">Manage subscription</Link></aside></section></main></div></div>
}
